name: Go Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  go-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.23.2
          cache: true
      - name: Run Tests
        run: go test -v ./... | tee test.log; exit ${PIPESTATUS[0]}
      - name: Analyze Test Time
        run: grep --color=never -e '--- PASS:' -e '--- FAIL:' test.log | sed 's/[:()]//g' | awk '{print $2,$3,$4}' | sort -t' ' -nk3 -r | awk '{sum += $3; print $1,$2,$3,sum"s"}'
      - name: Go Lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: -v